
//FIRST:myadress
export const RCAPTCHA_KEY_CLIENT ="6LeK3acUAAAAAO5360ooM6gmArYECIJFSF-4KSnJ"
export const RCAPTCHA_KEY_SERVER = "6LeK3acUAAAAAIlOz88T-5NFwBOvouscMtEEUp6k"

//SECOND:Platform
//export const RCAPTCHA_KEY_CLIENT = "6Le2rqkUAAAAAE0vFGRKZdbwv57ok2E_YUdWEHwV"
//export const RCAPTCHA_KEY_SERVER = "6Le2rqkUAAAAAEOVlSa_VZONYyF1wMkYb3d-wYhV"